# Generated by Django 3.2.8 on 2021-10-21 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0003_alter_image_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='title',
        ),
    ]
